services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - ./symfony:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/todo

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
