<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFAbFkE4\App_KernelLocalDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFAbFkE4/App_KernelLocalDebugContainer.php') {
    touch(__DIR__.'/ContainerFAbFkE4.legacy');

    return;
}

if (!\class_exists(App_KernelLocalDebugContainer::class, false)) {
    \class_alias(\ContainerFAbFkE4\App_KernelLocalDebugContainer::class, App_KernelLocalDebugContainer::class, false);
}

return new \ContainerFAbFkE4\App_KernelLocalDebugContainer([
    'container.build_hash' => 'FAbFkE4',
    'container.build_id' => '4a5666dc',
    'container.build_time' => 1753138231,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFAbFkE4');
